---
# Common project variables
project_name: "autopatroni"
domain: "infra.local"

# Hardware parameters
cpu: 1
ram: 2  # in GB
disk: 50 # in GB

# Patroni hosts
patroni1_hostname: "vmpatronidb-1"
patroni2_hostname: "vmpatronidb-2"
patroni3_hostname: "vmpatronidb-3"
patroni1_ip: "192.168.1.135"
patroni2_ip: "192.168.1.136"
patroni3_ip: "192.168.1.137"
# Leave empty to let ESXi auto-assign safe MAC addresses
patroni1_mac: ""
patroni2_mac: ""
patroni3_mac: ""

# Host FQDNs
patroni1_fqdn: "{{ patroni1_hostname }}.{{ domain }}"
patroni2_fqdn: "{{ patroni2_hostname }}.{{ domain }}"
patroni3_fqdn: "{{ patroni3_hostname }}.{{ domain }}"

# PostgreSQL version
pg_major_version: 15


# =========================
# Infrastructure / ESXi
# =========================
esxi_hostname: "esxi"
esxi_username: "root"
esxi_validate_certs: false
esxi_datacenter: "ha-datacenter"
esxi_datastore: "datastore1"
esxi_network_name: "VM Network"
esxi_folder: "/ha-datacenter/vm"
esxi_clone_source_vm: "ubuntutemplate"
esxi_guest_id: "ubuntu64Guest"
vm_hardware_version: 21
vm_disk_type: thin
vm_guest_memory_mb: "{{ ram | int * 1024 }}"
vm_guest_cpu: "{{ cpu | int }}"
esxi_guest_netmask: "255.255.255.0"
esxi_guest_gateway: "192.168.1.1"
esxi_guest_dns_servers:
  - "192.168.1.146"
# true for vCenter-based customization; false for standalone ESXi compatibility
esxi_guest_customization_enabled: false
# standalone clone backend: vmware_guest or govc
esxi_standalone_clone_backend: "vmware_guest"
esxi_govc_url: "https://{{ esxi_hostname }}"
esxi_govc_insecure: true

# Optional local/offline collection tarball path for community.vmware
community_vmware_collection_tarball: ""

# Clone workflow from prepared source VM
autoinstall_enabled: false

# =========================
# Initial OS bootstrap access (fresh Ubuntu)
# =========================
bootstrap_connect_user: "{{ bootstrap_user }}"
bootstrap_connect_password: "{{ aleksei_user_pass }}"
bootstrap_connect_become_password: "{{ bootstrap_connect_password }}"

# Final automation user that must exist on Patroni nodes
bootstrap_user: "aleksei"
bootstrap_password: "{{ aleksei_user_pass }}"


# Database objects
app_db_name: "{{ project_name }}"
app_schema_name: "{{ project_name }}"
app_user_name: "{{ project_name }}"

# PostgreSQL settings (calculated parameters)
# RAM in MB for calculations
ram_mb: "{{ ram * 1024 }}"

# shared_buffers
shared_buffers: >-
  {% if ram < 4 -%}
  {{ (ram_mb / 4) | int }} MB
  {%- else -%}
  {{ (ram / 4) | int }} GB
  {%- endif %}

# work_mem
work_mem: "{% if ram < 64 %}32 MB{% else %}64 MB{% endif %}"

# maintenance_work_mem
maintenance_work_mem: >-
  {% if ram < 32 -%}
  320 MB
  {%- elif ram >= 32 and ram < 64 -%}
  420 MB
  {%- else -%}
  640 MB
  {%- endif %}

# effective_cache_size
effective_cache_size: >-
  {% if ram < 4 -%}
  {{ (ram_mb * 0.7) | round(0) | int }} MB
  {%- else -%}
  {{ (ram * 0.7) | round(0) | int }} GB
  {%- endif %}

# Other PostgreSQL parameters
cpu_half: "{{ ((cpu + 1) / 2) | int }}"
archive_command: "/bin/true"
extensions: "pg_stat_statements"

# PG_HBA
#ldap_hba: "- host {{ app_db_name }} +ldap_users 0.0.0.0/0  ldap ldapscheme=ldaps ldapport=636 ldaptls=0 ldapserver=e-business.moscow.alfaintra.net ldapprefix="e-business\""
dba1_hba: "- host all all 192.168.58/32 scram-sha-256"
#dba2_hba: "- host all all ??????????/32 scram-sha-256"
#dba3_hba: "- host all all ??????????/32 scram-sha-256"
#dba4_hba: "- host all all ??????????/32 scram-sha-256"
app1_hba: "- host {{ app_db_name }} {{ app_user_name }} 192.168.143/32 scram-sha-256"
app2_hba: "- host {{ app_db_name }} {{ app_user_name }} 192.168.144/32 scram-sha-256"
#app3_hba: "- host {{ app_db_name }} {{ app_user_name }} ???????????/32 scram-sha-256"
#app4_hba: "- host {{ app_db_name }} {{ app_user_name }} ???????????/32 scram-sha-256"
#app5_hba: "- host {{ app_db_name }} {{ app_user_name }} ???????????/32 scram-sha-256"
#app6_hba: "- host {{ app_db_name }} {{ app_user_name }} ???????????/32 scram-sha-256"

# Variables to be loaded from Vault
# They are defined here as empty but will be populated when using the vault lookup plugin
vault_secrets:
  zabbix_monitor_pass: "{{ lookup('ansible.builtin.pipe', 'vault kv get -field=zbx_monitor_pass secret/patroni_dpl') | trim }}"
  app_user_pass: "{{ lookup('ansible.builtin.pipe', 'vault kv get -field=app_user_pass secret/patroni_dpl') | trim }}"
  postgres_user_pass: "{{ lookup('ansible.builtin.pipe', 'vault kv get -field=postgres_user_pass secret/patroni_dpl') | trim }}"
  ppem_agent_user_pass: "{{ lookup('ansible.builtin.pipe', 'vault kv get -field=ppem_agent_user_pass secret/patroni_dpl') | trim }}"
  otel_user_pass: "{{ lookup('ansible.builtin.pipe', 'vault kv get -field=otel_user_pass secret/patroni_dpl') | trim }}"
  backup_user_pass: "{{ lookup('ansible.builtin.pipe', 'vault kv get -field=backup_user_pass secret/patroni_dpl') | trim }}"
  postgres_exporter_user_pass: "{{ lookup('ansible.builtin.pipe', 'vault kv get -field=postgres_exporter_user_pass secret/patroni_dpl') | trim }}"
  zbx_monitor_user_pass: "{{ lookup('ansible.builtin.pipe', 'vault kv get -field=zbx_monitor_user_pass secret/patroni_dpl') | trim }}"
  auditor_user_pass: "{{ lookup('ansible.builtin.pipe', 'vault kv get -field=auditor_user_pass secret/patroni_dpl') | trim }}"
  ppem_api_key: "{{ lookup('ansible.builtin.pipe', 'vault kv get -field=ppem_api_key secret/patroni_dpl') | trim }}"
  admin_user_pass: "{{ lookup('ansible.builtin.pipe', 'vault kv get -field=admin_user_pass secret/patroni_dpl') | trim }}"
  replicator_user_pass: "{{ lookup('ansible.builtin.pipe', 'vault kv get -field=replicator_user_pass secret/patroni_dpl') | trim }}"
  rewind_user_pass: "{{ lookup('ansible.builtin.pipe', 'vault kv get -field=rewind_user_pass secret/patroni_dpl') | trim }}"
  aleksei_user_pass: "{{ lookup('ansible.builtin.pipe', 'vault kv get -field=aleksei_user_pass secret/patroni_dpl') | trim }}"
  esxi_pass: "{{ lookup('ansible.builtin.pipe', 'vault kv get -field=esxi_pass secret/patroni_dpl') | trim }}"
  
# For convenience, separate variables can be created
zbx_monitor_pass: "{{ vault_secrets.zabbix_monitor_pass }}"
app_user_pass: "{{ vault_secrets.app_user_pass }}"
postgres_user_pass: "{{ vault_secrets.postgres_user_pass }}"
ppem_agent_user_pass: "{{ vault_secrets.ppem_agent_user_pass }}"
otel_user_pass: "{{ vault_secrets.otel_user_pass }}"
backup_user_pass: "{{ vault_secrets.backup_user_pass }}"
postgres_exporter_user_pass: "{{ vault_secrets.postgres_exporter_user_pass }}"
zbx_monitor_user_pass: "{{ vault_secrets.zbx_monitor_user_pass }}"
auditor_user_pass: "{{ vault_secrets.auditor_user_pass }}"
ppem_api_key: "{{ vault_secrets.ppem_api_key }}"
admin_user_pass: "{{ vault_secrets.admin_user_pass }}"
replicator_user_pass: "{{ vault_secrets.replicator_user_pass }}"
rewind_user_pass: "{{ vault_secrets.rewind_user_pass }}"
aleksei_user_pass: "{{ vault_secrets.aleksei_user_pass }}"
esxi_pass: "{{ vault_secrets.esxi_pass }}"
esxi_password: "{{ vault_secrets.esxi_pass }}"
