{
 "title": "Backend Application Layer",
 "tags": [
  "nginx",
  "php-fpm",
  "backend",
  "wordpress"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "backend",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "group": { "filter": "WordPress Backends" },
     "host": { "filter": "$backend" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": { "filter": "Requests per second" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "group": { "filter": "WordPress Backends" },
     "host": { "filter": "$backend" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": { "filter": "Connections active" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "title": "PHP-FPM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Active Processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "group": { "filter": "WordPress Backends" },
     "host": { "filter": "$backend" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": { "filter": "Processes, active" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Idle Processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "group": { "filter": "WordPress Backends" },
     "host": { "filter": "$backend" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": { "filter": "Processes, idle" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Max Children Reached",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "group": { "filter": "WordPress Backends" },
     "host": { "filter": "$backend" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": { "filter": "Max children reached" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Slow Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "group": { "filter": "WordPress Backends" },
     "host": { "filter": "$backend" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": { "filter": "Slow requests" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Listen Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "group": { "filter": "WordPress Backends" },
     "host": { "filter": "$backend" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": { "filter": "Listen queue" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  }
 ]
}