{
 "title": "PostgreSQL Metrics",
 "tags": [
  "postgresql",
  "zabbix",
  "patroni",
  "database"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "group": {
      "filter": "/Patroni Cluster|Monitoring Stack/"
     },
     "host": { "filter": "$host" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": {
      "filter": "/Connections sum: (Total|Active|Idle|Waiting)/"
     },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Transactions per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "group": {
      "filter": "/Patroni Cluster|Monitoring Stack/"
     },
     "host": { "filter": "$host" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": {
      "filter": "/Dbstat: (Committed|Roll backed) transactions per second/"
     },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "group": {
      "filter": "/Patroni Cluster|Monitoring Stack/"
     },
     "host": { "filter": "$host" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": { "filter": "Cache hit ratio, %" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Database size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "group": {
      "filter": "/Patroni Cluster|Monitoring Stack/"
     },
     "host": { "filter": "$host" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": { "filter": "/DB \\[.*\\]: Database size/" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Rows returned / fetched per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "group": {
      "filter": "/Patroni Cluster|Monitoring Stack/"
     },
     "host": { "filter": "$host" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": {
      "filter": "/Dbstat: Rows (returned|fetched) per second/"
     },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Rows inserted / updated / deleted per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "group": {
      "filter": "/Patroni Cluster|Monitoring Stack/"
     },
     "host": { "filter": "$host" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": {
      "filter": "/Dbstat: Rows (inserted|updated|deleted) per second/"
     },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Locks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "group": {
      "filter": "/Patroni Cluster|Monitoring Stack/"
     },
     "host": { "filter": "$host" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": { "filter": "/DB \\[.*\\]: Num of .* locks/" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Uptime & Replication",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "group": {
      "filter": "/Patroni Cluster|Monitoring Stack/"
     },
     "host": { "filter": "$host" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": { "filter": "Uptime" },
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "group": {
      "filter": "/Patroni Cluster|Monitoring Stack/"
     },
     "host": { "filter": "$host" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": {
      "filter": "/Replication: (Lag in seconds|Status|Standby count)/"
     },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "WAL write / receive per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "group": {
      "filter": "/Patroni Cluster|Monitoring Stack/"
     },
     "host": { "filter": "$host" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": {
      "filter": "/WAL: Bytes (written|received)/"
     },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Deadlocks per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "group": {
      "filter": "/Patroni Cluster|Monitoring Stack/"
     },
     "host": { "filter": "$host" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": { "filter": "/Dbstat: Deadlocks per second/" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Bgwriter: Buffers per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "group": {
      "filter": "/Patroni Cluster|Monitoring Stack/"
     },
     "host": { "filter": "$host" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": {
      "filter": "/Bgwriter: Buffers.*per second/"
     },
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "group": {
      "filter": "/Patroni Cluster|Monitoring Stack/"
     },
     "host": { "filter": "$host" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": {
      "filter": "/Checkpoint: Buffers written.*per second/"
     },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Checkpoint: Write & Sync time per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "group": {
      "filter": "/Patroni Cluster|Monitoring Stack/"
     },
     "host": { "filter": "$host" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": {
      "filter": "/Checkpoint: (Requested|Scheduled|Checkpoint (write|sync) time) per second/"
     },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  }
 ]
}