{
 "title": "WebApp Overview",
 "tags": [
  "nginx",
  "php-fpm",
  "web",
  "overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Front Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Frontend — Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "group": { "filter": "Web Frontend" },
     "host": { "filter": "/.*/" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": { "filter": "Requests per second" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Frontend — Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "group": { "filter": "Web Frontend" },
     "host": { "filter": "/.*/" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": { "filter": "Connections active" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Frontend — Reading",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "group": { "filter": "Web Frontend" },
     "host": { "filter": "/.*/" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": { "filter": "Connections reading" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Frontend — Writing",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "group": { "filter": "Web Frontend" },
     "host": { "filter": "/.*/" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": { "filter": "Connections writing" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Frontend — Waiting",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "group": { "filter": "Web Frontend" },
     "host": { "filter": "/.*/" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": { "filter": "Connections waiting" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "title": "Backends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Backends — Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "group": { "filter": "WordPress Backends" },
     "host": { "filter": "/.*/" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": { "filter": "Requests per second" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Backends — Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "group": { "filter": "WordPress Backends" },
     "host": { "filter": "/.*/" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": { "filter": "Connections active" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Backends — PHP-FPM Active Processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "group": { "filter": "WordPress Backends" },
     "host": { "filter": "/.*/" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": { "filter": "Processes, active" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Backends — PHP-FPM Idle Processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "group": { "filter": "WordPress Backends" },
     "host": { "filter": "/.*/" },
     "application": { "filter": "" },
     "itemTag": { "filter": "" },
     "item": { "filter": "Processes, idle" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  }
 ]
}