all:
  children:
    esxi:
      hosts:
        esxi.infra.local:
          ansible_host: 192.168.1.83
    dns:
      hosts:
        vmubuntu-6.infra.local:
          ansible_host: 192.168.1.146
    patroni_nodes:
      hosts: {}
