---
all:
  children:
    dns:
      hosts:
        vmubuntu-6.infra.local:
          ansible_host: 192.168.1.146

    patroni_nodes:
      hosts:
        vmpatronidb-1:
          ansible_host: 192.168.1.135
        vmpatronidb-2:
          ansible_host: 192.168.1.136
        vmpatronidb-3:
          ansible_host: 192.168.1.137

    infra:
      hosts:
        vmubuntu-1:
          ansible_host: 192.168.1.141
        vmubuntu-2:
          ansible_host: 192.168.1.142
        vmubuntu-3:
          ansible_host: 192.168.1.143
        vmubuntu-4:
          ansible_host: 192.168.1.144
        vmubuntu-5:
          ansible_host: 192.168.1.145
        vmubuntu-7:
          ansible_host: 192.168.1.147
        vmubuntu-8:
          ansible_host: 192.168.1.148

    nfs_servers:
      hosts:
        vmubuntu-5:
          ansible_host: 192.168.1.145

    wordpress_backends:
      hosts:
        vmubuntu-3:
          ansible_host: 192.168.1.143
        vmubuntu-4:
          ansible_host: 192.168.1.144

    nginx_frontend:
      hosts:
        vmubuntu-1:
          ansible_host: 192.168.1.141

    backup:
      hosts:
        vmubuntu-5:
          ansible_host: 192.168.1.145

    backup_replica:
      hosts:
        vmubuntu-2:
          ansible_host: 192.168.1.142

    logging:
      hosts:
        vmubuntu-7:
          ansible_host: 192.168.1.147

    monitoring:
      hosts:
        vmubuntu-8:
          ansible_host: 192.168.1.148

    zabbix_api:
      hosts:
        zabbix-api-endpoint:
          ansible_host: 192.168.1.148
          ansible_connection: httpapi
          ansible_network_os: community.zabbix.zabbix
          ansible_httpapi_use_ssl: true
          ansible_httpapi_validate_certs: false
          ansible_httpapi_port: 443
          ansible_zabbix_url_path: ""
          ansible_user: Admin
