scope: {{ project_name }}_cluster
namespace: /service/
name: {{ patroni1_hostname }}
log:
  dir: /pgdata/patroni
  level: INFO
restapi:
  listen: {{ patroni1_ip }}:8008
  connect_address: {{ patroni1_ip }}:8008

etcd3:
  hosts: {{ patroni1_ip }}:2379, {{ patroni2_ip }}:2379, {{ patroni3_ip }}:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true

  initdb:
    - encoding: UTF8
    - data-checksums

  pg_hba:
    - local all all trust
    - host all all 127.0.0.1/32 trust
    - local replication all trust
    - host replication all 127.0.0.1/32 trust
    - host replication replicator 127.0.0.1/32 scram-sha-256
    - host replication replicator {{ patroni1_ip }}/32 scram-sha-256
    - host replication replicator {{ patroni2_ip }}/32 scram-sha-256
    - host replication replicator {{ patroni3_ip }}/32 scram-sha-256
    - host all all {{ patroni1_ip }}/32 scram-sha-256
    - host all all {{ patroni2_ip }}/32 scram-sha-256
    - host all all {{ patroni3_ip }}/32 scram-sha-256
    - host all all 0.0.0.0/0 scram-sha-256

  users:
    admin:
      password: {{ admin_user_pass }}
      options:
        - createrole
        - createdb

postgresql:
  listen: 127.0.0.1,{{ patroni1_ip }}:5432
  connect_address: {{ patroni1_ip }}:5432
  data_dir: /pgdata/{{ pg_major_version }}/data
  config_dir: /pgdata/{{ pg_major_version }}/data
  bin_dir: /usr/lib/postgresql/{{ pg_major_version }}/bin
  pgpass: /tmp/pgpass
  use_unix_socket: /var/lib/pgsql/
  authentication:
    replication:
      username: replicator
      password: {{ replicator_user_pass }}
    superuser:
      username: postgres
      password: {{ postgres_user_pass }}
    rewind:
      username: rewind
      password: {{ rewind_user_pass }}

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
